--- ## (Leandro Lemos - 2018/01)

- name: Starting realted tasks to fix variant one of spectre and/or variant three (aka meltdown)          
  include: startPatching.yaml
  when: variantOne == "VULN" or variantThree == "VULN"        

- fail: msg="The system is not vulnerable to variant one and three, but it is to variant 2 (no patches yet)"
  when: variantOne != "VULN" and variantThree != "VULN" and variantTwo == "VULN"

- name: Rebooting servers          
  include: rebootServers.yaml
  when: inventory_hostname in groups['withReboot'] or rebootServers == "yes" or rebootServers == "y" and updateState.changed == "true"
  register: wasRebooted        

- name: Generating report about if the server was rebooted under "{{ pathRebootReport }}"
  local_action:
    module: lineinfile
    line: "The server {{ inventory_hostname }} was rebooted {{ wasRebooted.changed }}"
    state: present        
    insertafter: EOF        
    create: yes        
    path: "{{ pathRebootReport }}"

- name: Running checks of vulnerabilities once more time
  include_role:
    name: checkVulnerability        
  vars:
    statVulnReport: 1         

## eof
