--- ## (Leandro Lemos - 2018/01)

- name: Rebooting servers
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  register: wasRebooted
  when: (rebootServers == "yes" or rebootServers == "y") and updateState.changed == "true"

- name: Waiting for server to come back
  wait_for_connection:
    timeout: 300
    delay: 60
  when: (rebootServers == "yes" or rebootServers == "y") and updateState.changed == "true"

## eof
