--- ## (Leandro Lemos - 2018/01)

- name: Rebooting servers
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  register: wasRebooted

- name: Waiting for server to come back
  wait_for_connection:
    timeout: 600
    delay: 60

## eof
