--- ## (Leandro Lemos - 2018/01)

- include_vars:
    file: main.yaml

- name: Getting script for check vulnerabilitys
  get_url:
    url: "{{ scriptUrl }}"
    dest: "{{ resideScript }}"
    mode: 0760

- name: Checking if the system is vulnerable
  shell: "{{ resideScript }} --batch"
  register: isVulnerable        
  failed_when: isVulnerable.rc == 255        

#- debug:
#  var: isVulnerable

- set_fact:
    variantOne: 
      "{{ isVulnerable.stdout_lines[0] | regex_search('(VULN)') }}"    

- set_fact:
    variantTwo: 
      "{{ isVulnerable.stdout_lines[1] | regex_search('(VULN)') }}"    

- set_fact:
    variantThree: 
      "{{ isVulnerable.stdout_lines[2] | regex_search('(VULN)') }}"    

- name: Generating report about if the server is vulnerable under "{{ pathReportVulnerabilites }}"
  local_action:
    module: lineinfile
    line: "The server {{ inventory_hostname }} has the next state: \
           variant 1: {{ variantOne }}
           variant 2: {{ variantTwo }}
           variant 3: {{ variantThree }}"
    state: present                  
    insertafter: EOF
    create: yes        
    path: "{{ pathReportVulnerabilites }}"
  when: postPatch == 1            
     
## eof      
