--- ## (Leandro Lemos - 2018/01)

scriptUrl: https://raw.githubusercontent.com/speed47/spectre-meltdown-checker/master/spectre-meltdown-checker.sh
resideScript: /tmp/spectre-meltdown-checker.sh

## eof
